### ISSUE TITLE
need gamma dataset

### ISSUE THREAD

**Issue by liuliuyu618** [master-Shix/ETSCL#1]
Hello author, I am currently researching glaucoma and urgently need a gamma dataset. As this competition has ended, I have not found any channels to obtain the gamma 300 pairs dataset. Could you please share with me this dataset or any other channels to obtain the gamma 300 pairs dataset？

**Comment by liuliuyu618** [comment]
Hello author, I am currently researching glaucoma and urgently need a gamma dataset. As the GAMA2021 has ended, I have not found any channels to obtain the gamma 300 pairs dataset. Could you please share with me this dataset or any other channels to obtain the gamma 300 pairs dataset？

**Comment by tczbzb** [comment]
you can try here:

https://ichallenges.grand-challenge.org/ichallenge-download/

Thanks,

Bo

**Comment by tczbzb** [comment]
Actually the link does not work now...let me ask around for you...

**Comment by liuliuyu618** [comment]
Yes, this competition has ended and the dataset cannot be obtained from this link. And I have been collecting for a long time, but have not found any channels to obtain this dataset. Could you please add my contact information or share it with my email 1822616276@qq.com Thank you very much~

**Comment by tczbzb** [comment]
I'd suggest you email the corresponding author of the GAMMA paper (
https://www.sciencedirect.com/science/article/abs/pii/S1361841523001986?via%3Dihub)
, since they own the dataset. Thanks.

**Comment by liuliuyu618** [comment]
Okay, I'll give it a try. Thank you very much!

**Comment by AllenYT** [comment]
> Okay, I'll give it a try. Thank you very much!

Do you now have the complete GAMMA data? Thank you very much~

**Comment by tczbzb** [comment]
You can find the gamma dataset here: http://hdmilab.cn/ichallenge
