### ISSUE TITLE
a question about OCT model's dim

### ISSUE THREAD

**Issue by liuliuyu618** [master-Shix/ETSCL#2]
for  you readme of  ## Training
why the dim of OCT model when i train it is [b,3,w,h], but when i use pth of OCT model in Stage 2, the dim of it is [b,128,w,h]?
Is there some kind of transformation going on in there? 
By the time I got to step two, the model was reporting this error that could not be trained.

**Comment by Yufei2000** [comment]
Maybe you can try for main_supcon_thick.py file, line 137, change it, 
x = x[125:128, :, :] to this #x = x[::2, :, :] 
x = x[::2, :, :]  # Now the shape is (128, 512, 512) 
x = x[125:128, :, :] # Now the shape is (3, 512, 512), 
comment line 137, uncomment line 136.

**Comment by liuliuyu618** [comment]
Thank you very much for your answer~
